# Generated by Django 4.1.7 on 2023-03-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="fullname",),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=100),
        ),
    ]
