# Generated by Django 4.1.7 on 2023-04-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='minimum_score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
