# Generated by Django 4.1.7 on 2023-03-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_identity_address_and_more'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantCustomColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=100)),
                ('column_value', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
        ),
    ]
