# Generated by Django 4.1.7 on 2023-04-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_identity_address_and_more'),
        ('application', '0002_applicantcustomcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(max_length=30)),
                ('collateral_value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
            preserve_default=False,
        ),
    ]
