# Generated by Django 4.1.7 on 2023-04-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_collateral_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='interest_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('Flat', 'Flat'), ('Anuitas 78', 'Anuitas 78'), ('Anuitas', 'Anuitas'), ('Efektif', 'Efektif'), ('Sliding', 'Sliding')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('Modal Kerja', 'Modal Kerja'), ('Investasi', 'Investasi'), ('Konsumsi', 'Konsumsi')], max_length=30, null=True),
        ),
    ]
