# Generated by Django 4.1.7 on 2023-04-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loanproduct", "0002_alter_loanproduct_create_date_and_more"),
        ("application", "0005_collateral_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="loan_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loanproduct.loanproduct",
            ),
        ),
    ]
