# Generated by Django 4.1.7 on 2023-04-12 07:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="scores",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), size=None
            ),
        ),
    ]
