# Generated by Django 4.1.7 on 2023-04-21 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0002_alter_section_minimum_score"),
        ("loanproduct", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanproduct",
            name="create_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="update_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="LoanProductSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "loan_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loanproduct.loanproduct",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="section.section",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("loan_product", "section")},
            },
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="sections",
            field=models.ManyToManyField(
                through="loanproduct.LoanProductSection", to="section.section"
            ),
        ),
    ]
