# Generated by Django 4.1.7 on 2023-05-07 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loanproduct', '0003_loanproduct_deleted_at_loanproduct_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
