# Generated by Django 4.1.7 on 2023-04-21 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question", "0002_alter_question_scores"),
        ("answer", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer", unique_together={("question", "user")},
        ),
    ]
