# Generated by Django 4.1.7 on 2023-04-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0005_collateral_application"),
        ("answer", "0002_alter_answer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="application",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.application",
            ),
            preserve_default=False,
        ),
    ]
