# Generated by Django 4.1.7 on 2023-04-21 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicant", "0009_applicantfile"),
        ("answer", "0003_answer_application"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="application",),
        migrations.AddField(
            model_name="answer",
            name="applicant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="applicant.applicant",
            ),
            preserve_default=False,
        ),
    ]
