# Generated by Django 4.1.7 on 2023-04-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answer", "0004_remove_answer_application_answer_applicant"),
    ]

    operations = [
        migrations.RemoveField(model_name="answer", name="applicant",),
    ]
