# Generated by Django 4.1.7 on 2023-04-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answer", "0005_remove_answer_applicant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="answer", unique_together=set(),),
        migrations.RemoveField(model_name="answer", name="chosen",),
        migrations.RemoveField(model_name="answer", name="user",),
    ]
