# Generated by Django 4.1.7 on 2023-04-21 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0002_alter_section_minimum_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applicant", "0009_applicantfile"),
        ("survey", "0002_survey_filler"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="survey", unique_together={("filler", "applicant", "section")},
        ),
    ]
