# Generated by Django 4.1.7 on 2023-05-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_remove_survey_final_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="final_score",
            field=models.IntegerField(default=0),
        ),
    ]
