# Generated by Django 4.1.7 on 2023-05-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0006_application_loan_product"),
        ("section", "0002_alter_section_minimum_score"),
        ("survey", "0006_survey_final_score"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="survey", unique_together={("application", "section")},
        ),
    ]
