# Generated by Django 4.1.7 on 2023-03-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='domicie_district',
            new_name='domicile_district',
        ),
    ]
