# Generated by Django 4.1.7 on 2023-03-04 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_alter_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
