# Generated by Django 4.1.7 on 2023-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_application_status_applicant_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='identity_address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='identity_city',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='identity_district',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='identity_postal_code',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='identity_subdistrict',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin'), ('Cerai', 'Cerai')], default='Belum Kawin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='office_address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='office_business_type',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='office_department',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='office_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='office_phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen Protestan', 'Kristen Protestan'), ('Kristen Katolik', 'Kristen Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu'), ('Agama Lainnya', 'Agama Lainnya')], default='Islam', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
