# Generated by Django 4.1.7 on 2023-04-19 09:16

import applicant.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_identity_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=applicant.models.generate_path)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
        ),
    ]
