# Generated by Django 4.1.7 on 2023-04-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0009_applicantfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicant',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
