# Generated by Django 4.1.7 on 2023-05-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0010_applicant_update_by_applicant_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='applicantfile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
