# Generated by Django 4.1.7 on 2023-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applicant",
            "0011_applicantfile_deleted_at_applicantfile_deleted_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="branch",
            field=models.CharField(default="Pusat", max_length=100),
        ),
    ]
